3 - Added IDL files in json
vyper-protocol/vyper-sdk pull request #16
Opened 2022-12-27 18:41 UTC by Shikhar15606

Added the idl files in json format. 
Fix #3

2022-12-28 09:30 UTC, thegreat-vanderlinde requested changes

2022-12-28 09:30 UTC, thegreat-vanderlinde commented on src/index.ts
> +export * from './idls/ts'
can we export from here the json files as well?

2022-12-29 19:20 UTC, Shikhar15606 commented on src/index.ts
> +export * from './idls/ts'
@thegreat-vanderlinde we can do that. Done

2022-12-30 13:18 UTC, thegreat-vanderlinde approved these changes

2022-12-30 13:18 UTC, merged