11 - receive supabase client in function
vyper-protocol/vyper-sdk pull request #17
Opened 2022-12-27 18:51 UTC by Shikhar15606

Fixes #11

2022-12-28 09:38 UTC, thegreat-vanderlinde requested changes

2022-12-28 09:38 UTC, thegreat-vanderlinde commented on src/api/supabase/notificationTrigger.ts
>  const currentCluster = 'devnet' as Cluster;
we should refactor this module in order to remove the hardcoded `currentCluster` from here. the methods that use it should receive it as a parameter

2022-12-29 18:54 UTC, Shikhar15606 commented on src/api/supabase/notificationTrigger.ts
>  const currentCluster = 'devnet' as Cluster;
@thegreat-vanderlinde I forgot to fix that in #13 
It is now fixed in this pr

2022-12-30 13:20 UTC, thegreat-vanderlinde approved these changes

2022-12-30 13:20 UTC, merged